# Generated by Django 5.0.3 on 2024-05-19 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0002_todo_subject_alter_todo_createdat_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todo',
            options={'ordering': ['deadline']},
        ),
        migrations.RenameField(
            model_name='todo',
            old_name='subject',
            new_name='project',
        ),
        migrations.AddField(
            model_name='todo',
            name='description',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
